INSERT INTO TB_CATEGORY(CATEGORY_NO, CATEGORY_NM, CATEGORY_DESC, REG_ID, REG_DTM)      
VALUES('CAT000000001', '에어컨', '에어컨 카테고리입니다.', 'admin', to_char(sysdate, 'YYYYMMDDHH24MISS'))  ; 

INSERT INTO TB_CATEGORY(CATEGORY_NO, CATEGORY_NM, CATEGORY_DESC, REG_ID, REG_DTM)      
VALUES('CAT000000002', '세탁기', '세탁기 카테고리입니다.', 'admin', to_char(sysdate, 'YYYYMMDDHH24MISS'))  ; 
 
INSERT INTO TB_CATEGORY(CATEGORY_NO, CATEGORY_NM, CATEGORY_DESC, REG_ID, REG_DTM)      
VALUES('CAT000000003', '냉장고', '냉장고 카테고리입니다.', 'admin', to_char(sysdate, 'YYYYMMDDHH24MISS'))  ; 

INSERT INTO TB_CATEGORY(CATEGORY_NO, CATEGORY_NM, CATEGORY_DESC, REG_ID, REG_DTM)      
VALUES('CAT000000004', 'TV', 'TV 카테고리입니다.', 'admin', to_char(sysdate, 'YYYYMMDDHH24MISS'))  ; 

INSERT INTO TB_CATEGORY(CATEGORY_NO, CATEGORY_NM, CATEGORY_DESC, REG_ID, REG_DTM)      
VALUES('CAT000000005', '노트북', '노트북 카테고리입니다.', 'admin', to_char(sysdate, 'YYYYMMDDHH24MISS'))  ; 
 
INSERT INTO TB_CATEGORY(CATEGORY_NO, CATEGORY_NM, CATEGORY_DESC, REG_ID, REG_DTM)      
VALUES('CAT000000006', '카메라', '카메라 카테고리입니다.', 'admin', to_char(sysdate, 'YYYYMMDDHH24MISS'))  ; 

